output_bags:
  - uri: /home/joseph/TurtleDel/turtledel_bag_filtered
    storage_id: sqlite3
    topics:
      - /battery_state
      - /clicked_point
      - /cliff_intensity
      - /cmd_lightring
      - /cmd_vel
      - /diagnostics
      - /diagnostics_agg
      - /diagnostics_toplevel_state
      - /dock_status
      - /events/write_split
      - /function_calls
      - /hazard_detection
      - /hmi/display
      - /imu
      - /initialpose
      - /interface_buttons
      - /ip
      - /ir_intensity
      - /ir_opcode
      - /joint_states
      - /joy
      - /kidnap_status
      - /mobility_monitor/transition_event
      - /mouse
      - /oakd/rgb/preview/camera_info
      - /odom
      - /parameter_events
      - /pose
      - /rfid
      - /robot_description
      - /robot_state/transition_event
      - /rosout
      - /scan
      - /slam_toolbox/graph_visualization
      - /slam_toolbox/scan_visualization
      - /slam_toolbox/update
      - /slip_status
      - /static_transform/transition_event
      - /stop_status
      - /tf
      - /tf_static
      - /waypoints
      - /wheel_status
      - /wheel_ticks
      - /wheel_vels
